# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_document_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='lname',
            field=models.CharField(default='lastname', max_length=100),
            preserve_default=False,
        ),
    ]
