# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import myproject.myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170414_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='choice',
            field=models.CharField(choices=[(b'1', b'Narrative'), (b'2', b'Documentary')], default=b'1', max_length=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=b'documents/%Y/%m/%d', validators=[myproject.myapp.validators.validate_mime_type]),
        ),
    ]
