# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170415_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Title', max_length=100),
            preserve_default=False,
        ),
    ]
