# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.CharField(default='thumbnail', max_length=100),
            preserve_default=False,
        ),
    ]
