# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import myproject.myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_document_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='choice',
            field=models.CharField(choices=[('1', 'Narrative'), ('2', 'Documentary')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[myproject.myapp.validators.validate_mime_type]),
        ),
    ]
