# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 21:21
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20170422_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
