# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-09 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_document_netid'),
        ('myapp', '0008_auto_20170506_2121'),
    ]

    operations = [
    ]
