# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:08
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/Users/haochenli/Documents/COS333/official/tigercinema/myproject/myapp/static/thumbnails'), upload_to=''),
        ),
    ]
