# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_document_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='position',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
