# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20170512_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='position',
        ),
    ]
